CXX = g++
CXXFLAGS= -g -std=c++11
LDFLAGS = -lgecodedriver -lgecodesearch -lgecodeminimodel \
       -lgecodeint -lgecodekernel -lgecodesupport

BINS = checker cp plot

all: $(BINS)

clean:
	rm -rf $(BINS)
